name = "supm3n"
pages_build_output_dir = "./dist"

# Connect the D1 Database
[[d1_databases]]
binding = "DB" # This matches 'env.DB' in your API code
database_name = "supm3n-db"
database_id = "xxxx-xxxx-xxxx-xxxx" # We don't need a real ID for local dev